### ISSUE TITLE
Day02 - Logistic Regression

### ISSUE THREAD

**Issue by Talasta** [42-AI/bootcamp_machine-learning#4]
# Day02: Logistic Regression

## Math
- [x] Sigmoid
- [x] Logistic Cost Function
- [x] Logistic Gradient Descent
- [x] Vectorized Logistic Cost Function
- [x] Vectorised Logistic Gradient Descent

## Algorithm
- [x] Logistic Regression

## Model Evaluation
- [x] Accuracy
- [x] Precision
- [x] Recall
- [x] F1 Score
- [x] Confusion matrix

## Todo
- [x] Check together if the content and format of the day is good

**Comment by bcarlier75** [comment]
Done : sigmoid (version vectorisée) + Vectorized Logistic Cost Function + Vectorised Logistic Gradient Descent

Pas sur de l'interet de leur faire coder une version non vectorisée cela dit, ça pourrait etre assez frustrant de devoir faire deux exos assez longs avec plein de boucles pour decouvrir juste ensuite qu'il leur faut une ligne 😅. A discuter donc

**Comment by Talasta** [comment]
> Done : sigmoid (version vectorisée) + Vectorized Logistic Cost Function + Vectorised Logistic Gradient Descent
> 
> Pas sur de l'interet de leur faire coder une version non vectorisée cela dit, ça pourrait etre assez frustrant de devoir faire deux exos assez longs avec plein de boucles pour decouvrir juste ensuite qu'il leur faut une ligne 😅. A discuter donc

Je penses qu'une version non vectorisée permet de bien assimiler ce qu'il se passe, mais de manière non optimisé, après tu fais la version opti avec numpy IMO.
Si on fait direct la version vectorisée, il est possible que certaines personnes passe a coté de ce que font les functions.
Après ça se discute toujours.

**Comment by bcarlier75** [comment]
Oui j'imagine que certaines personnes auront plus de facilité dans un premier dans avec des fonctions faisant appel a des boucles qu'à prendre en main directement la multiplication de vecteurs/matrices. On en reparlera lundi de toute façon tous ensemble 👍.

Concernant l'avancement, tout ce qui est coché est fait sauf pour Logistic Regression qui est en cours. J'ai rajouté confusion matrix je trouve que c'est important de connaitre le concept et de savoir a quoi correspondent les chiffres. C'est dans le prolongement de precision, recall et f1 score.
